### ISSUE TITLE
Segfault Crash on any GM script execution in x86_64 Linux self compile

### ISSUE THREAD

**Issue by ensiform** [jswigart/omni-bot#23]
Manjaro Linux x86_64 latest stable
Self compile using BOOST systemlib 1.76.0-2
The affected callstack shows from the weapon_defaults.gm (the first executed file usually?) but it also happens if you execute anything from the console command script run as well.
![codetree](https://user-images.githubusercontent.com/997399/147353715-d49f1a33-8ceb-47f1-8183-2dd107e499a6.png)

Has anyone experienced problems like this in the gmex dep source before?

**Comment by plastovicka** [comment]
Have you compiled ET:Legacy yourself, or have you downloaded version 2.79 from their website ?

**Comment by ensiform** [comment]
I'm not using etlegacy of any kind, and will not be. Custom OB build for ETF mod but I have switched to using the 0.83 code and fixed up TFLib to be compile-able.

**Comment by plastovicka** [comment]
It's hard to debug C++ apps on Linux, because all libraries in a Linux process share the same memory heap. That means that your ET engine, your ETF mod and Omni-bot use the same memory allocator. If some library overwrites memory structures, then it can crash later when another library needs memory. It is much easier and safer on Windows where DLLs are separated. Each DLL on Windows has its own memory heap and address range.
That call stack trace is irrelevant because this bug is not in Omni-bot. The bug is somewhere in your ET engine. Why don't you want to use ET:Legacy ? They had exactly the same problem in their code, but they somehow fixed it in the last version.

**Comment by ensiform** [comment]
After discussing with the ET Legacy dev, it appears the `stable` OB branch is pointing to an outdated gmscriptex module without the 64-bit fix(es) among others.

https://github.com/jswigart/omni-bot/tree/stable/0.83/Omnibot/dependencies `gmscriptex @ e740174` 

https://github.com/jswigart/gmscriptex/commits/master

**Comment by plastovicka** [comment]
Thanks. I fixed the submodule dependency now.
